### ISSUE TITLE
可以把源码放出来吗，也许我们可以帮忙完善呢

### ISSUE THREAD

**Issue by zh2250635** [KtzeAbyss/Easy-Virtual-Display#19]

**Comment by KtzeAbyss** [comment]
源码请关注parsec vdd项目

**Comment by kira1928** [comment]
@KtzeAbyss 
目前这个程序是完全闭源的，尤其安装包和 app 都不属于 parsec vdd 项目，只能靠你这边开源了。
说实话安装没有强大商业公司背书的闭源二进制文件，尤其还是驱动相关的应用程序，作为用户是有点心虚的 T_T

**Comment by KtzeAbyss** [comment]
> @KtzeAbyss 目前这个程序是完全闭源的，尤其安装包和app都不属于parsec vdd项目，只能靠你开源了。 说实话安装没有强大商业公司背书的闭源二进制文件，尤其还是驱动相关的应用程序，作为用户是有点心虚的T_T

驱动是parsec vdd官方驱动
