### ISSUE TITLE
[功能请求]能否增加更多刷新率选项

### ISSUE THREAD

**Issue by lzy0702** [KtzeAbyss/Easy-Virtual-Display#20]
为了与多种不同的屏幕适配，90, 120, 165Hz等，如果能自定义支持的刷新率列表最好

**Comment by zh2250635** [comment]
https://support.parsec.app/hc/en-us/articles/4423615425293
可以自己添加任意分辨率和刷新率

**Comment by ViktorRezonv** [comment]
安装Release版的`EasyVirtualDisplay 0.1` ，在注册表中看不到这个地址：
`\HKEY_LOCAL_MACHINE\SOFTWARE\Parsec\vdd`
请问如何解决？

**Comment by KtzeAbyss** [comment]
> 安装Release版的`EasyVirtualDisplay 0.1` ，在注册表中看不到这个地址： `\HKEY_LOCAL_MACHINE\SOFTWARE\Parsec\vdd` 请问如何解决？

自己创建即可，已经过测试可行
