### ISSUE TITLE
关于sunshine的指定显示器

### ISSUE THREAD

**Issue by duanyunlun** [KtzeAbyss/Easy-Virtual-Display#21]
因为目前版本的EVD还不支持”开机启动+自动创建+创建时固定显示ID”或“一旦创建永不丢失”的特性，我在sunshine串流设置中的这个就经常需要手动去指定：
![image](https://github.com/KtzeAbyss/Easy-Virtual-Display/assets/15923235/0ad5f826-5afd-494a-8928-4e147ae76d4c)

希望能增加以一个固化虚拟显示器的选项，即创建后即使重启PC，该虚拟显示器依然存在，且对应途中的Output Display是固定的。

**Comment by KtzeAbyss** [comment]
可关注parsec vdd项目，parsec vdd即将提供更好的解决方案

**Comment by happyTonakai** [comment]
@KtzeAbyss 该项目目前似乎只有驱动，没有开箱即用的app

**Comment by ddkk3000** [comment]
> @KtzeAbyss 该项目目前似乎只有驱动，没有开箱即用的app

这个项目什么都没有啊。

**Comment by KtzeAbyss** [comment]
> > @KtzeAbyss该项目目前似乎只有驱动，没有开箱即用的应用程序
> 
> 这个项目什么都没有啊。

抱歉，我也不知道为什么作者一直没有放出应用程序，本项目目前只进行最低限度的维护，作为一个临时替代方案使用
