### ISSUE TITLE
win10虚拟显示器识别不到，如下图。

### ISSUE THREAD

**Issue by supermangithu** [KtzeAbyss/Easy-Virtual-Display#9]
![11](https://github.com/KtzeAbyss/Easy-Virtual-Display/assets/69227320/ef414d61-ab21-4314-a7f9-4c2248bd2b07)
win10虚拟显示器识别不到，如图。请问怎么解决？

**Comment by KtzeAbyss** [comment]
从你的图中，似乎parsec vdd驱动没有正常安装？

**Comment by jeffery1996** [comment]
https://support.parsec.app/hc/en-us/articles/4422939339789
同样的问题，发现parsec vdd驱动需要 ＞Win10 21H2
